# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Android CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    env:
        api-level: 29
        java-version: 11

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ env.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.java-version }}
          distribution: 'adopt'
          cache: 'gradle'

      - name: Run unit tests
        run: ./gradlew build --dry-run

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: ${{ runner.os }}-${{ env.api-level }}-${{ env.java-version }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run Android tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedAndroidTest --dry-run
